export enum Status {
  ACTIVE,
  SPEAKING_TIME,
  SPEAKING_TIME_END,
  REWIEW_TIME,
  REWIEW_TIME_END,
  QUESTION_TIME,
  QUESTION_TIME_END,
  LASTWORD_TIME,
  LASTWORD_TIME_END,
  ALL_TIME,
  DONE
}
